// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR35n6GjesnfQ5Glgu6p4l7jxC2sZk0Po',
    appId: '1:506053933565:web:6052add1d0f6ea3ed78194',
    messagingSenderId: '506053933565',
    projectId: 'ehky-chat-app',
    authDomain: 'ehky-chat-app.firebaseapp.com',
    storageBucket: 'ehky-chat-app.firebasestorage.app',
    measurementId: 'G-8S3V0MS5N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDNuF7F6cuvhmAmESP00-OReyagNjWVQ',
    appId: '1:506053933565:android:2d1197a171a41981d78194',
    messagingSenderId: '506053933565',
    projectId: 'ehky-chat-app',
    storageBucket: 'ehky-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrih4vgOmjjoAmuIuA19tqKZcP9WcUu4',
    appId: '1:506053933565:ios:c7f27bbb165ea3fad78194',
    messagingSenderId: '506053933565',
    projectId: 'ehky-chat-app',
    storageBucket: 'ehky-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.ehkyChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrih4vgOmjjoAmuIuA19tqKZcP9WcUu4',
    appId: '1:506053933565:ios:c7f27bbb165ea3fad78194',
    messagingSenderId: '506053933565',
    projectId: 'ehky-chat-app',
    storageBucket: 'ehky-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.ehkyChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR35n6GjesnfQ5Glgu6p4l7jxC2sZk0Po',
    appId: '1:506053933565:web:2021f357b4dd8e28d78194',
    messagingSenderId: '506053933565',
    projectId: 'ehky-chat-app',
    authDomain: 'ehky-chat-app.firebaseapp.com',
    storageBucket: 'ehky-chat-app.firebasestorage.app',
    measurementId: 'G-RFZR6Y4WB8',
  );
}
